---
- name: Configure App
  hosts: app
  become: true
  vars:
   db_host: 35.233.20.201
  
  roles:
   - app
   - jdauphant.nginx

  handlers:
  - name: reload puma
    systemd: name=puma state=reloaded



